import Head from 'next/head'
import Image from 'next/image'
import styles from './login.module.css'




export default function Login() {



 
 
  return (
   
    <div className={styles.container} >
     
     
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>
         <Image className={styles.banner} src="/src/img/login_name.png" alt="title" width={1280} height={300} />
      <div className={styles.below_banner}>
       <button className={styles.login_button} >
        <h2>ログイン</h2>
      </button>
      </div>

     </main>
     </div>
   

  )
}
