import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './User_home.module.css'


export default function User() {
  return (

    <div className={styles.container}>
      <Head>
        <title>社員ページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

      <main >
        <header className={styles.header}>
        <Image src="/MIKpage_title_white.jpg" alt="title" width={683} height={138} />
        </header>
      

      <div className={styles.userinfo}>
        <div>
          <div className={styles.userinfo1}>
          <Image src="/userphoto1.png" alt="user1" width={167} height={159}/>
          <h2>井上真美</h2>
          </div>

          <div className={styles.userinfo2}>
            <h3>入社日</h3> 
            <p>2022年10月1日</p>
            <h3>派遣先</h3> 
            <p>株式会社ABC</p>
            <h3>派遣開始</h3> 
            <p>2022年10月1日</p>
           </div>
        </div>
      </div>
      <div className={styles.userinfo_contents }>
        <h2>現在の状況</h2>
        <a>
        <h3>現在の保有ポイント</h3>
        <p>100pt</p>
        </a>
        <a>
        <h3>有給残日数</h3>
        <p>10日</p>
        </a>
        <a>
        <h3>年次研修予定日</h3>
        <p>2022年12月5日</p>
        </a>
      </div>

      <div className={styles.notice}>
        <h3>MIKからのお知らせ</h3>
        <p>2022/12/9 メンタルヘルスチェック結果を送りました。</p>
      </div>
    
        <ul className={styles.buttonarea}>
          <li>
            <a className={styles.selectbutton} href="user/contribute_point">
              <h2>社内貢献ポイント</h2>
            </a>
          </li>
          <li>
            <a className={styles.selectbutton} href="user/paid_time_off">
              <h2>有給休暇利用</h2>
            </a>
          </li>
          <li>
            <a className={styles.selectbutton} href="user/learning">
              <h2>研修</h2>
            </a>
          </li>
          <li>
            <a className={styles.selectbutton} href="user/career_consul">
              <h2>キャリア相談</h2>
            </a>
          </li>
          <li>
            <a className={styles.selectbutton} href="user/phase">
              <h2>フェーズ</h2>
            </a>
          </li>
          <li>
            <a className={styles.selectbutton} href="user/contact">
              <h2>緊急連絡先</h2>
            </a>
          </li>
        </ul>
   
      </main>
     </div>
  )
}
